const GAMES={645:{name:'Mega 6/45',max:45,pick:6,url:'https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/power645.jsonl'},655:{name:'Power 6/55',max:55,pick:6,url:'https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/power655.jsonl'},535:{name:'Lotto 5/35',max:35,pick:5,url:'https://raw.githubusercontent.com/vietvudanh/vietlott-data/main/data/power535.jsonl'}};
let game='645',draws=[],frequencies=[],currentTickets=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], pad=n=>String(n).padStart(2,'0');
function seededDraws(max,pick,count=100){let seed=max*997+pick;return Array.from({length:count},()=>{const a=[];while(a.length<pick){seed=(seed*9301+49297)%233280;const n=1+Math.floor(seed/233280*max);if(!a.includes(n))a.push(n)}return a.sort((x,y)=>x-y)})}
function parseLines(text,cfg){const out=[];for(const line of text.trim().split(/\n+/)){try{const o=JSON.parse(line);const pool=[];const walk=v=>{if(Array.isArray(v))v.forEach(walk);else if(typeof v==='number')pool.push(v);else if(v&&typeof v==='object')Object.values(v).forEach(walk)};walk(o.result||o.numbers||o);const nums=pool.filter(n=>Number.isInteger(n)&&n>=1&&n<=cfg.max);const unique=[...new Set(nums)].slice(0,cfg.pick);if(unique.length===cfg.pick)out.push(unique.sort((a,b)=>a-b))}catch{}}return out}
async function loadData(){const cfg=GAMES[game];$('#dataStatus').classList.remove('ready');$('#dataStatus').innerHTML='<i></i> Đang nạp dữ liệu';try{const res=await fetch(cfg.url);if(!res.ok)throw Error();const parsed=parseLines(await res.text(),cfg);if(parsed.length<30)throw Error();draws=parsed.slice(-200).reverse();$('#dataStatus').innerHTML='<i></i> Dữ liệu cộng đồng · '+draws.length+' kỳ';}catch{draws=seededDraws(cfg.max,cfg.pick,100);$('#dataStatus').innerHTML='<i></i> Chế độ dữ liệu mô phỏng';}$('#dataStatus').classList.add('ready');analyze();generate()}
function analyze(){const cfg=GAMES[game],sample=draws.slice(0,100);frequencies=Array(cfg.max+1).fill(0);sample.forEach(d=>d.forEach(n=>frequencies[n]++));const sums=sample.map(d=>d.reduce((a,b)=>a+b,0));const avg=Math.round(sums.reduce((a,b)=>a+b,0)/sums.length);$('#avgSum').textContent=avg;$('#sumRange').textContent=`vùng ${Math.min(...sums)}–${Math.max(...sums)}`;const patterns={};sample.forEach(d=>{const e=d.filter(n=>n%2===0).length;patterns[e]=(patterns[e]||0)+1});const even=+Object.entries(patterns).sort((a,b)=>b[1]-a[1])[0][0];$('#oddEven').textContent=`${even} / ${cfg.pick-even}`;$('#quality').textContent=sample.length>=100?'Tốt':'Khá';renderHeat(cfg);const sorted=[...Array(cfg.max)].map((_,i)=>i+1).sort((a,b)=>frequencies[b]-frequencies[a]);balls('#hotNums',sorted.slice(0,5));balls('#coldNums',sorted.slice(-5).reverse());const last={};draws.forEach((d,i)=>d.forEach(n=>{if(last[n]===undefined)last[n]=i}));balls('#dueNums',[...Array(cfg.max)].map((_,i)=>i+1).sort((a,b)=>(last[b]??999)-(last[a]??999)).slice(0,5));renderBands(cfg,sample)}
function renderHeat(cfg){const ordered=frequencies.slice(1).slice().sort((a,b)=>a-b),low=ordered[Math.floor(ordered.length*.2)],high=ordered[Math.floor(ordered.length*.8)];$('#heatmap').innerHTML=[...Array(cfg.max)].map((_,i)=>{const n=i+1,f=frequencies[n],state=f>=high?'high':f<=low?'low':'normal',bg=state==='high'?'#e75045':state==='low'?'#c9e8f8':'#eef0ec',color=state==='high'?'#fff':'#183d39';return `<div class="heat-cell" title="${pad(n)} xuất hiện ${f} lần — ${state==='high'?'nhóm nhiều':state==='low'?'nhóm ít':'mức bình thường'}" style="background:${bg};color:${color}">${pad(n)}<small>${f}×</small></div>`}).join('')}
function renderBands(cfg,sample){const ranges=[];for(let s=1;s<=cfg.max;s+=10)ranges.push([s,Math.min(s+9,cfg.max)]);const vals=ranges.map(([a,b])=>sample.reduce((z,d)=>z+d.filter(n=>n>=a&&n<=b).length,0)/sample.length);const max=Math.max(...vals);$('#bands').innerHTML=ranges.map((r,i)=>`<div class="band"><i style="height:${20+vals[i]/max*85}px"></i><b>${vals[i].toFixed(1)}</b><br>${pad(r[0])}–${pad(r[1])}</div>`).join('')}
function balls(sel,nums){$(sel).innerHTML=nums.map(n=>`<i class="ball">${pad(n)}</i>`).join('')}
function pickTicket(cfg,strategy){const nums=[...Array(cfg.max)].map((_,i)=>i+1),last={};draws.forEach((d,i)=>d.forEach(n=>{if(last[n]===undefined)last[n]=i}));const weighted=nums.map(n=>{let w=1;if(strategy==='frequency'||strategy==='ensemble')w+=frequencies[n]*1.4;if(strategy==='overdue'||strategy==='ensemble')w+=(last[n]||0)*.7;if(strategy==='hotcold')w+=Math.abs(frequencies[n]-(draws.length*cfg.pick/cfg.max));return {n,w:w*(.82+Math.random()*.36)}});const selected=[];while(selected.length<cfg.pick){const available=weighted.filter(x=>!selected.includes(x.n));const total=available.reduce((s,x)=>s+x.w,0);let r=Math.random()*total,chosen=available[0].n;for(const x of available){r-=x.w;if(r<=0){chosen=x.n;break}}selected.push(chosen)}return selected.sort((a,b)=>a-b)}
function reasonFor(n){const cfg=GAMES[game],ordered=frequencies.slice(1).slice().sort((a,b)=>a-b),lo=ordered[Math.floor(ordered.length*.2)],hi=ordered[Math.floor(ordered.length*.8)];let gap=draws.findIndex(d=>d.includes(n));if(gap<0)gap=draws.length;const signals=[];if(frequencies[n]>=hi)signals.push(`tần suất cao (${frequencies[n]} lần)`);else if(frequencies[n]<=lo)signals.push(`tần suất thấp (${frequencies[n]} lần)`);else signals.push(`tần suất cân bằng (${frequencies[n]} lần)`);if(gap>=Math.max(6,Math.round(cfg.max/cfg.pick)))signals.push(`vắng ${gap} kỳ`);signals.push(n%2?'số lẻ':'số chẵn');signals.push(`nhóm ${pad(Math.floor((n-1)/10)*10+1)}–${pad(Math.min(Math.floor((n-1)/10)*10+10,cfg.max))}`);return signals}
function explainTicket(i){const t=currentTickets[i],sum=t.reduce((a,b)=>a+b,0),even=t.filter(n=>n%2===0).length;$('#explainDetail').innerHTML=`<p><b>Bộ #${pad(i+1)}</b> · Tổng ${sum} · ${even} chẵn / ${t.length-even} lẻ</p><div class="reason-row">${t.map(n=>`<span class="reason-chip"><b>${pad(n)}</b> · ${reasonFor(n).join(' · ')}</span>`).join('')}</div><p class="note">Đây là lý do xếp hạng theo chiến lược đã chọn, không có nghĩa mỗi số có xác suất quay cao hơn.</p>`;$('#explainDetail').classList.add('show')}
function generate(){const cfg=GAMES[game],count=+$('#ticketCount').value,strategy=$('#strategy').value;currentTickets=[];for(let i=0;i<count;i++){let t;do{t=pickTicket(cfg,strategy)}while(currentTickets.some(x=>x.join()==t.join()));currentTickets.push(t)}$('#resultTitle').textContent=`${cfg.name} · ${count} bộ`;$('#tickets').innerHTML=currentTickets.map((t,i)=>`<div class="ticket"><span>#${pad(i+1)}</span><div class="balls">${t.map(n=>`<i class="ball">${pad(n)}</i>`).join('')}</div><button class="why-btn" onclick="explainTicket(${i})">Vì sao?</button></div>`).join('');$('.tag').textContent='CHƯA LƯU';$('#explainDetail').classList.remove('show')}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id))}
function save(){const records=JSON.parse(localStorage.getItem('xsForecasts')||'[]');records.unshift({id:Date.now(),game:GAMES[game].name,tickets:currentTickets,strategy:$('#strategy').selectedOptions[0].text,window:+$('#window').value,created:new Date().toLocaleString('vi-VN')});localStorage.setItem('xsForecasts',JSON.stringify(records));$('.tag').textContent='ĐÃ LƯU';$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200);renderHistory()}
function deleteForecast(id){if(!confirm('Xóa dự báo đã lưu này?'))return;const records=JSON.parse(localStorage.getItem('xsForecasts')||'[]').filter(r=>r.id!==id);localStorage.setItem('xsForecasts',JSON.stringify(records));renderHistory();$('#toast').textContent='Đã xóa dự báo';$('#toast').classList.add('show');setTimeout(()=>{$('#toast').classList.remove('show');$('#toast').textContent='Đã lưu dự báo thành công'},1800)}
function renderHistory(){const records=JSON.parse(localStorage.getItem('xsForecasts')||'[]');$('#historyList').innerHTML=records.length?records.map(r=>`<div class="history-card"><div><h3>${r.game}</h3><small>${r.created}</small></div><div>${r.tickets.map(t=>`<div class="balls small" style="margin:5px 0">${t.map(n=>`<i class="ball">${pad(n)}</i>`).join('')}</div>`).join('')}</div><small>${r.strategy}<br>${r.window} kỳ</small><button class="delete-btn" title="Xóa dự báo" aria-label="Xóa dự báo" onclick="deleteForecast(${r.id})">×</button></div>`).join(''):'<div class="empty">Chưa có dự báo nào được lưu.<br>Hãy tạo một dự báo để bắt đầu nhật ký kiểm chứng.</div>'}
$$('.nav').forEach(n=>n.onclick=()=>showView(n.dataset.view));$$('.game').forEach(b=>b.onclick=()=>{$$('.game').forEach(x=>x.classList.remove('active'));b.classList.add('active');game=b.dataset.game;loadData()});$('#ticketCount').oninput=e=>$('#ticketValue').textContent=e.target.value+' bộ';$('#generate').onclick=generate;$('#regenerate').onclick=generate;$('#save').onclick=save;$('#clearHistory').onclick=()=>{localStorage.removeItem('xsForecasts');renderHistory()};renderHistory();loadData();
